import { Employee } from "./employee";

export const EMPLOYEE: Array<Employee> = [
    {
        id: 1,
        codeName: "Amiya",
        hp_base: 700,
        atk_base: 270,
        def_base: 50,
        hp_e1: 900,
        atk_e1: 390,
        def_e1: 61,
        hp_e2: 1480,
        atk_e2: 612,
        def_e2: 121,
        artResist: 10,
        block: 1,
        redeploy: 70,
        cost: 18,
        interval: 1.6,
        sk1:'01_sk1',
        sk2:'01_sk2',
        sk3:'01_sk3',
        desc:'Amiya, leader of Rhodes Island, will fight alongside you.',
        profile:"The public face of Rhodes Island and its top executive.\nAlthough Amiya appears to be a young and inexperienced girl, she is universally trusted and highly qualified for her position.\n"+
                "Amiya now leads the island in fighting for the future of the Infected and striving to exorcise the dark shadow of Originium from the land.",
        cynical1:"[Cell-Originium Assimilation] 19% ",
        cynical2:"[Blood Originium-Crystal Density] 0.27u/L ",
        cynical3:"???",
    },
    {
        id: 2,
        codeName: "Ch`en",
        hp_base: 1220,
        atk_base: 239,
        def_base: 154,
        hp_e1: 2188,
        atk_e1: 469,
        def_e1: 288,
        hp_e2: 2880,
        atk_e2: 610,
        def_e2: 352,
        artResist: 0,
        block: 1,
        redeploy: 70,
        cost: 23,
        interval: 1.3,
        sk1:'02_sk1',
        sk2:'02_sk2',
        sk3:'02_sk3',
        desc:'Ch`en, Special Inspection Unit Chief, L.G.D., is cooperating with Rhodes Island to fulfill the obligations outlined in her contract. ',
        profile:"Ch'en, head of the Lungmen Guard Department's Special Inspection Unit, graduated from the Royal Victorian Guard School with superb grades and outstanding achievements. During her time with the Department, she cracked down on crime, fought violent offenders, tracked down armed fugitives, and brought down international criminals. Now works at Rhodes Island, providing on-site tactical command.",
        cynical1:"[At the request of the Lungmen Guard Department, this information will not be made public.]She did come in for a physical examination, but her files have been confiscated. I have no way to get them. Why? I was told not to.--Medic Operator R.T.",
        cynical2:"[Originium Overview]Ch`en has never been seen using Originium, which led many to suspect she didn`t have a talent for it. Indeed, she did struggle to control her Originium ability, blasting the occasional hole in a wall, blowing files everywhere, and causing more collateral damage than might otherwise be acceptable. Using Originium for too long tires her out. After discussion with the tech staff, it was decided Ch'en lacked the necessary conduit to control her Originium power. Without one, Ch`en could never master it. ",
        cynical3:"Ch'en graduated from the Royal Victorian Guard School with straight A's in all mandatory subjects and glowing recommendations from her professors. After returning to Lungmen, she almost immediately joined the Guard Department. ",
    },
    {
        id: 3,
        codeName: "Texas",
        hp_base: 727,
        atk_base: 203,
        def_base: 139,
        hp_e1: 1365,
        atk_e1: 410,
        def_e1: 274,
        hp_e2: 1950,
        atk_e2: 500,
        def_e2: 343,
        artResist: 0,
        block: 2,
        redeploy: 70,
        cost: 11,
        interval: 1.05,
        sk1:'03_sk1',
        sk2:'03_sk2',
        sk3:'none',
        desc:'Texas, employee of Penguin Logistics, will give the squad a tactical advantage with her Originium Arts at the start of every battle. ',
        profile:"Texas is a Penguin Logistics staff member who is extraordinarily skilled in single combat. She was sent to Rhodes Island as a liaison, where she assists with a variety of operations.",
        cynical1:"[Cell-Originium Assimilation] 0%Operator Texas showed no symptoms of Oripathy. ",
        cynical2:"[Blood Originium-Crystal Density] 0.12u/LOperator Texas sometimes delivers packages with Originium content, but it has not caused infection to date.",
        cynical3:"While Texas may be quiet, her fighting style is anything but. It's best described as tempestuous.At Rhodes Island, Operators without formal training are actually the majority, but when it comes to the use of weapons, most will follow established protocols.",
    },
    {
        id: 4,
        codeName: "Zima",
        hp_base: 812,
        atk_base: 183,
        def_base: 147,
        hp_e1: 1505,
        atk_e1: 376,
        def_e1: 290,
        hp_e2: 2150,
        atk_e2: 470,
        def_e2: 350,
        artResist: 0,
        block: 2,
        redeploy: 70,
        cost: 13,
        interval: 1.05,
        sk1:'03_sk1',
        sk2:'04_sk2',
        sk3:'none',
        desc:'Zima, Vanguard Operator of Rhodes Island, will give the squad a tactical advantage with her physical strength at the start of every battle. ',
        profile:"Before the Chernobog incident, Zima was a middle school student. In school, she displayed a peculiar interest in fighting and violence. Multiple tests have shown she has the strength and solid constitution characteristic of the Ursus race.Currently, she leads a squad of Vanguard Operators.",
        cynical1:"[Cell-Originium Fusion Rate] 0% Operator shows no signs of infection at this time.",
        cynical2:"[Blood Crystal Density] 0.1u/L This Operator has rarely come into contact with Originium.",
        cynical3:"Zima defies most people's preconceived notions what an Ursus should be, expecting her to be irascible and sensitive. When she has something to say, she says it directly, and doesn't much consider what kind of impact it's going to leave her targets. What is certain is that Zima feels her words and actions are acceptable. Even so, as soon as she feels like one of her friends is being bullied or treated unfairly, she will stick up for them regardless of the circumstances.",
    },
    {
        id: 5,
        codeName: "Kross",
        hp_base: 545,
        atk_base: 154,
        def_base: 52,
        hp_e1: 1060,
        atk_e1: 375,
        def_e1: 126,
        hp_e2: 1480,
        atk_e2: 400,
        def_e2: 210,
        artResist: 0,
        block: 1,
        redeploy: 70,
        cost: 11,
        interval: 1,
        sk1:'05_sk1',
        sk2:'none',
        sk3:'none',
        desc:'Kroos, Sniper Operator of Rhodes Island, will interrupt the enemies attacks with her crossbow. ',
        profile:"The public face of Rhodes Island and its top executive. Although Amiya appears to be a young and inexperienced girl, she is universally trusted and highly qualified for her position.<br>"+
                "Amiya now leads the island in fighting for the future of the Infected and striving to exorcise the dark shadow of Originium from the land.",
        cynical1:"[Cell-Originium Fusion Rate] 8% She presents no obvious external symptoms of Oripathy.",
        cynical2:"[Blood Crystal Density] 0.23u/L Degree of infection is minor and physical symptoms are not yet present.",
        cynical3:"Kroos prefers put in the absolute minimum effort in life and on the battlefield, which is reflective of her weapon of choice - a modern crossbow. Despite her lazy work ethic, Kroos has become a skilled marksman and assists her fellow Operators by flanking the enemy and shooting them in the rear with deadly precision.",
    },
    {
        id: 6,
        codeName: "Blue Poison",
        hp_base: 536,
        atk_base: 176,
        def_base: 45,
        hp_e1: 984,
        atk_e1: 348,
        def_e1: 109,
        hp_e2: 1230,
        atk_e2: 535,
        def_e2: 130,
        artResist: 5,
        block: 1,
        redeploy: 70,
        cost: 13,
        interval: 1,
        sk1:'06_sk1',
        sk2:'06_sk2',
        sk3:'none',
        desc:'Blue Poison, Sniper Operator of Rhodes Island, will attack the enemy with her venom. ',
        profile:"Blue Poison (BP) is a lovely girl with a terrifying ability. She was recruited by Rhodes Island due to her natural talent in creating toxins. Now she serves as a Sniper operator and attacks enemies with poisoned darts. She’s able to deliver DPS, attack multiple targets and even deal Arts damage with her toxins.",
        cynical1:"???",
        cynical2:"???",
        cynical3:"???",
    },

]